# <center>Pandas Assignment</center>

Import pandas and numpy with their aliases

In [275]:
import pandas as pd
import numpy as np

Create a variable a = pd.Series([ 100, 200, 300, 400])

In [276]:
# a = 
a = pd.Series([100,200,300,400])

Print a, and data type

In [277]:
print(a,type(a))

0    100
1    200
2    300
3    400
dtype: int64 <class 'pandas.Series'>

Using indexing access the element 300 from the series a.

In [278]:

a[2]

np.int64(300)

What are the values of index for series a?

In [279]:

print(a.index)

RangeIndex(start=0, stop=4, step=1)

Change the index to  ['c', 'a', 'b', 'd']

In [280]:
a.index =  ['c', 'a', 'b', 'd']
print(a)

c    100
a    200
b    300
d    400
dtype: int64

Access the value in the series with index 'd'

In [281]:


a['d']

np.int64(400)

Sort the values wrt to the index and print it

In [282]:

print(a.sort_index())

a    200
b    300
c    100
d    400
dtype: int64

Create a new Pandas Series b having index as 'e', 'f', and 'g' and value 800,450,100 and print it

In [283]:
# b = 
b = pd.Series([800, 400, 100], index = ['e','f', 'g'])
print(b)

e    800
f    400
g    100
dtype: int64

Append b series at the end of a series

In [284]:
# a =
a =pd.concat([a,b])
print(a)

c    100
a    200
b    300
d    400
e    800
f    400
g    100
dtype: int64

In [285]:
#print a again after appending b into it

print(a)

c    100
a    200
b    300
d    400
e    800
f    400
g    100
dtype: int64

Sort the values in descending order of a and print the index of the sorted series

In [286]:
# a = 

a.sort_index(ascending = False)
print(a)

c    100
a    200
b    300
d    400
e    800
f    400
g    100
dtype: int64

In [287]:

print(a.index)

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='str')

## Pandas DataFrame

### Part 1

Create a pandas dataframe df from the series 'a' that we used in the last section, print the dataframe

In [288]:
# df = 

df = pd.DataFrame(a)

In [289]:
print(df)

     0
c  100
a  200
b  300
d  400
e  800
f  400
g  100

What is the shape of the datafarme <br>
(also, what does it imply?)

In [290]:

print(df.shape)   # 7 rows 1 column

(7, 1)

Hey! remember shape (7,1) implies dataframe has 7 rows and 1 column.

What is the index of the dataframe, is it same as the series 'a'

In [291]:
# yep its same as the series.
df.index      #same as a series

Index(['c', 'a', 'b', 'd', 'e', 'f', 'g'], dtype='str')

print the head and tail of the dataframe. <br>
Additional - (what does head and tali represent?)

In [292]:
print(df.head())
print(df.tail())

     0
c  100
a  200
b  300
d  400
e  800
     0
b  300
d  400
e  800
f  400
g  100

In [293]:
# head shows first 5 rows and tail shows last 5 rows of the dataframe.

Rename the column of the dataframe as 'points'

In [294]:
df.columns = ['points']

print(df)

   points
c     100
a     200
b     300
d     400
e     800
f     400
g     100

Create another Series 'fruits', which contains random names of fruits from ['orange','mango','apple']. The series should contain 7 elements, randomly selected from ['orange','mango','apple']

In [295]:
#Create fruits array

fruits = pd.Series(['orange', 'mango', 'apple', 'mango', 'orange', 'apple', 'mango'])
print(fruits)

0    orange
1     mango
2     apple
3     mango
4    orange
5     apple
6     mango
dtype: str

In [296]:
#Create series fruits out of fruits array

fruits = pd.Series(fruits)

Change the index of fruits to the index of dataframe df

In [297]:
fruits.index = df.index
print(fruits)

c    orange
a     mango
b     apple
d     mango
e    orange
f     apple
g     mango
dtype: str

Add this fruits series as a new column to the dataframe df with its column name as 'fruits'
<br>print the head of the dataframe to verify

In [298]:

df['fruits'] = fruits

In [299]:
print(df.head())

   points  fruits
c     100  orange
a     200   mango
b     300   apple
d     400   mango
e     800  orange

## Pandas Concatenation

Create a dataframe  d1 where the cols are  ‘city’ : [‘Chandigarh’, ‘Delhi’, ‘Kanpur’, ‘Chennai’, ‘Manali’ ] and ‘Temperature’ : [15, 22, 20, 26,-2]

In [300]:
 d1 = pd.DataFrame({'city': ['Chandigarh', 'Delhi', 'Kanpur', 'Chennai', 'Manali'],
 'temperature': [15,22,20,26,-2]})

Print(d1)

In [301]:

print(d1)

         city  temperature
0  Chandigarh           15
1       Delhi           22
2      Kanpur           20
3     Chennai           26
4      Manali           -2

What is the shape of d1.

In [302]:

d1.shape

(5, 2)

Set city = d1['city']

In [303]:

city = d1['city']

print city <br>
What is the type of city.

In [304]:
print(city)

print(type(city))

0    Chandigarh
1         Delhi
2        Kanpur
3       Chennai
4        Manali
Name: city, dtype: str
<class 'pandas.Series'>

Create another datafeame 'd2' where the columns are <br>
'city' - ['Bengalaru','Coimbatore','Srirangam','Pondicherry'] <br>
'Temperature' - [24,35,36,39]

In [305]:
d2 = pd.DataFrame({'city': ['Bengalaru','Coimbatore', 'Srirangam', 'Pondicherry'],
'temperature' : [24,35,36,39]})

print the shape of this dataframe

In [306]:
print(d2.shape)

(4, 2)

merge the two dataframes together, save it in a new dataframe named 'd3'

In [307]:
d3 = pd.concat([d1, d2])
print(d3)

          city  temperature
0   Chandigarh           15
1        Delhi           22
2       Kanpur           20
3      Chennai           26
4       Manali           -2
0    Bengalaru           24
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

Select the part of the dataframe such that it contains cities wherer temp is less then or equal to 20 <br>
How many cities are there?

Select the part of the dataframe such that it contains the cities where tempearature greater than or equal to 35

In [308]:
print(d2[d2['temperature'] <= 20])

print(d2[d2['temperature'] >= 35])

Empty DataFrame
Columns: [city, temperature]
Index: []
          city  temperature
1   Coimbatore           35
2    Srirangam           36
3  Pondicherry           39

## Applying functions to columns and creating new columns

We need to create another column in d3, which contains  a boolean value for each city to indicate whether it's a union territory or not. 
- HINT: Chandigarh, Pondicherry and Delhi are only 3 union territories here.

In [321]:
# write function here
d3['is_UT'] = d3['city'].isin(['Chandigarh', 'Pondicherry', 'Delhi'])

def is_ut(x):
    return x in ['Chandigarh', 'Pondicherry', 'Delhi']

d3['is_ut'] = d3['city'].apply(is_ut)

In [310]:
print(d3)

          city  temperature  is_UT  is_ut
0   Chandigarh           15   True   True
1        Delhi           22   True   True
2       Kanpur           20  False  False
3      Chennai           26  False  False
4       Manali           -2  False  False
0    Bengalaru           24  False  False
1   Coimbatore           35  False  False
2    Srirangam           36  False  False
3  Pondicherry           39   True   True

The temperatures mentioned in ‘Temperature’ column are mentioned in Celsius, we need another column which contains the same in Fahrenheit.

HINT - 
- Define a function c_to_f which takes input temp in celsius and returns a value with temperature in Fahrenheit.
- To check: c_to_f(10) should return 50.

In [311]:
# write function here

def c_to_f(x):
    return (x * 9/5) + 32

In [312]:
# check function c_to_f(10)

print(c_to_f(10))

50.0

In [313]:
# apply function c_to_f to d3 to create a column 'temp_farenhiet'

d3['temperature_f'] = d3['temperature'].apply(c_to_f)

d3

          city  temperature  is_UT  is_ut  temperature_f
0   Chandigarh           15   True   True           59.0
1        Delhi           22   True   True           71.6
2       Kanpur           20  False  False           68.0
3      Chennai           26  False  False           78.8
4       Manali           -2  False  False           28.4
0    Bengalaru           24  False  False           75.2
1   Coimbatore           35  False  False           95.0
2    Srirangam           36  False  False           96.8
3  Pondicherry           39   True   True          102.2

## Indexing and selecting rows in DataFrame

Select subset of the dataframe d1 such that it contains the cities which are union territories.

In [327]:
d1
d1['is_UT'] = d1['city'].isin(['Chandigarh', 'Pondicherry', 'Delhi'])
result = d1[d1['is_UT']]
print(result)

         city  temperature  is_UT
0  Chandigarh           15   True
1       Delhi           22   True

Select a subset of the dataframe d1 such that it contains the cities which only have temperature above 90 Farenhiet.

In [331]:
print(d1)
print(d1['temperature']) 
result = d1[d1['temperature'] > 32.22]
print(result)

         city  temperature  is_UT
0  Chandigarh           15   True
1       Delhi           22   True
2      Kanpur           20  False
3     Chennai           26  False
4      Manali           -2  False
0    15
1    22
2    20
3    26
4    -2
Name: temperature, dtype: int64
Empty DataFrame
Columns: [city, temperature, is_UT]
Index: []

Select only the first three rows of the dataframe d1.

In [332]:
d1.head(3)

         city  temperature  is_UT
0  Chandigarh           15   True
1       Delhi           22   True
2      Kanpur           20  False

Select all the rows and last two columns in the dataframe.

In [ ]:
d1.iloc[:, -2:]

   temperature  is_UT
0           15   True
1           22   True
2           20  False
3           26  False
4           -2  False

## Groupby

In [336]:
# Create a dataframe using dictionary of your choice

data = {
    'Name': ['Amit', 'Rahul', 'Priya'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Mumbai', 'Chennai']
}

df = pd.DataFrame(data)
print(df)

    Name  Age     City
0   Amit   20    Delhi
1  Rahul   21   Mumbai
2  Priya   19  Chennai

In [337]:
# Use Groupby of single column with aggregate sum()

df.groupby('City').sum()

          Name  Age
City
Chennai  Priya   19
Delhi     Amit   20
Mumbai   Rahul   21

In [338]:
# Use Groupby of single column with aggregate count()
df.groupby('City').count()

         Name  Age
City
Chennai     1    1
Delhi       1    1
Mumbai      1    1

In [339]:
# Use Groupby of single column with aggregate min() and max()
df.groupby('City').agg(['min', 'max'])

          Name        Age
           min    max min max
City
Chennai  Priya  Priya  19  19
Delhi     Amit   Amit  20  20
Mumbai   Rahul  Rahul  21  21

In [340]:
# Use Groupby of any 2 columns with aggregate mean()

df.groupby(['City', 'Name']).mean()

                Age
City    Name
Chennai Priya  19.0
Delhi   Amit   20.0
Mumbai  Rahul  21.0

In [342]:
# Use Groupby of any 2 columns with aggregate min() and max()
df.groupby(['City', 'Name']).agg(['min', 'max'])

              Age
              min max
City    Name
Chennai Priya  19  19
Delhi   Amit   20  20
Mumbai  Rahul  21  21

In [343]:
df

    Name  Age     City
0   Amit   20    Delhi
1  Rahul   21   Mumbai
2  Priya   19  Chennai

## Data Range

Create a pandas daterange where starting date is 1st of January,2020 and end date is 1st of April 2021, store it in a new variable named 'a'

In [344]:
a = pd.date_range(start='2020-01-01',end= '2021-04-01')

print a

In [345]:

print(a)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10',
               ...
               '2021-03-23', '2021-03-24', '2021-03-25', '2021-03-26',
               '2021-03-27', '2021-03-28', '2021-03-29', '2021-03-30',
               '2021-03-31', '2021-04-01'],
              dtype='datetime64[us]', length=457, freq='D')

What is the len of a?

In [347]:

print(len(a))

457

What is the type of a?

In [348]:


type(a)

pandas.DatetimeIndex